#!/bin/bash

# Configuration
[ -n "$BIN_HOME" ] \
    && dir="$BIN_HOME" \
    || dir="$HOME/.local/bin"

usage() {
    echo "addscript -- create boilerplate executable file and edit"
    echo
    echo "Usage: addscript NAME"
    exit 1
}

[ -z "$1" ] || [ "$1" = "-h" ] && usage

filename="$dir/$1"

# File already exists
[ -f "$filename" ] && $EDITOR "$filename" && exit

# File does not exist
echo -e "#!/bin/sh\n\n" > "$filename"
chmod +x "$filename"
$EDITOR "$filename"

