#!/bin/sh

# Find all files with the .$1 extention, lets you choose one, then exec with $2.

# theme="-theme sidebar"
theme=""

_filter_files() {
    for ext in $(echo $1 | tr "," "\n"); do
        du -a $HOME --exclude=".*" | cut -f2 | grep "\.$ext$"
    done
}

file=`_filter_files "$1" | sort | rofi -width 75% -dmenu -i $theme -p :`

[ "$file" = "" ] && exit

[ "$2" = "$EDITOR" ] && [ "$3" = "-" ] && $TERMINAL -e "$EDITOR \"$file\"" && exit

"$2" "$file"

#xargs -r -d "\n" "$2"
