#!/bin/sh

# Configuration
#theme="-theme sidebar"
selector="rofi -width 75% -dmenu -i $theme -p :"

usage() {
    echo "dugrep -- finds all files with the .\$1 extention"
    echo "          lets you choose one, then exec with \$2."
    echo
    echo "USAGE"
    echo "\tdugrep EXT EXE [-]"
    echo
    echo "\tUse \"-\" to open EXE in a new terminal."
    exit 1
}

[ -z "$1" ] || [ -z "$2" ] || [ "$1" = "-h" ] \
    && usage


filter_files() {
    for ext in $(echo "$1" | tr "," "\n"); do
        du -a $HOME --exclude=".*" | cut -f2 | grep "\.$ext$"
    done
}

file=$(filter_files "$1" | sort | $selector)
[ -z "$file" ] && exit

[ "$3" = "-" ] \
    && $TERMINAL -e "$2 \"$file\"" && exit

$2 "$file"

#xargs -r -d "\n" "$2"

