#!/bin/sh

m="$(date '+%_M' | tr -d ' ' )"

if [ $m = "0" ]; then
		M=""
elif [ $m -lt "15" ]; then
		M="$m over"
elif [ $m -eq "15" ]; then
		M="Kvart over"
elif [ $m -lt "30" ]; then
		d="$(expr 30 - $m)"
		M="$d på halv"
elif [ $m -eq "30" ]; then
		M="Halv"
elif [ $m -lt "45" ]; then
		d="$(expr $m - 30)"
		M="$d over halv"
elif [ $m -eq "45" ]; then
		M="Kvart på"
else
		d="$(expr 60 - $m)"
		M="$d på"
fi

h="$(date '+%_I' | tr -d ' ')"
[ $m -gt "15" ] && h="$(date -d '1 hour' '+%_I' | tr -d ' ')"

the_time="$M $h"

while getopts nd o; do
	case $o in
		n) the_time="$the_time på $(date '+%A')";;
		d) the_time="$the_time den $(date '+%_d. %B')";;
	esac
done

echo "$the_time"
