#!/bin/bash

pomodoro() {
	sleep "$1"
	notify-send -u critical -t 0 "Pomo" "$2"
	mpv "$HOME/shanti55.ogg"
}

countdown() {
	m=$(($1 * 60))
	start="$(( $(date '+%s') + $m))"
	while [ $start -ge $(date +%s) ]; do
		time="$(( $start - $(date +%s) ))"
		printf "\\r%s minutes untill $2" "$(date -u -d "@$time" +%-M)"
		sleep 0.2
	done
	notify-send -u critical -t 0 "Pomo" "$2"
	mpv "$HOME/shanti55.ogg"
}

case "$1" in
	"break"|"-b")
		t="5"
		[ -n "$2" ] && t="$2"
		countdown "$t" "Break is done."
		;;
	"start"|"-s")
		t="25"
		[ -n "$2" ] && t="$2"
		countdown "$t" "Pomodoro is done."
		;;
	"-h"|*)
		echo "usage: pomo [option]"
		echo
		echo "options:"
		echo "    -s, start DURATION  -- start a pomodoro lasting for DURATION (default: 25m)"
		echo "    -b, break DURATION  -- take a break lasting for DURATION (default: 5m)"
esac

