#!/bin/sh

[ "$1" = "" ] && echo "no file provided" && exit
[ ! -f "$1" ] && echo "no such file: $1" && exit

tmp_md="/tmp/printmd_$1.md"
tmp_pdf="/tmp/printmd_$1.pdf"

cp "$1" "$tmp_md"

echo '<style>html { font-family: "PT Serif", serif } body { max-width: 100%; padding: 0; } h3, h4, h5, h6 { margin-bottom: -0.75em; } h2 { border-bottom: 1px solid; page-break-before: always; } img { display: block; margin: auto; }</style>' >> "$tmp_md"

pandoc -s -t html -o "$tmp_pdf" "$tmp_md"

lpr "$tmp_pdf"
rm "$tmp_pdf"

