#!/bin/bash

if [ $# -eq 1 ]; then
    selected=$1
else
    dirs=$(find ~/src ~/work -mindepth 1 -maxdepth 1 -type d -follow 2>/dev/null)
	dirs=$(echo -e "$dirs\n$HOME/bin\n$HOME/.local/tools")
    selected=$(echo "$dirs" | sed "s|$HOME|~|" | fzf)
fi

if [ -z $selected ]; then
    exit 0
fi

selected_name=$(basename $selected | tr . _)

if [ -z "$(tmux ls 2>/dev/null | grep "^$selected_name")" ]; then
	tmux new-session -ds $selected_name -c $selected
fi

[ -z "$TMUX" ] \
	&& tmux attach-session -t $selected_name \
	|| tmux switch-client -t $selected_name

