#!/bin/sh

data_dir="$XDG_DATA_HOME/xkbutil"
[ ! -d "$data_dir" ] && mkdir -p "$data_dir"
layout_file="$dir/current-layout"

_set () {
	setxkbmap "$1" && echo "$1" > "$layout_file"
}

_toggle() {
	if [ -f "$layout_file" ]; then
		layout="$(cat $layout_file)"
		case $layout in
			"no") _set "ru";;
			"ru") _set "no";;
		esac
	fi
}

[ "$1" = "toggle" ] && _toggle && exit 0
[ "$1" = "set" ] && [ "$2" != "" ] && _set "$2" && exit 0

echo "Usage: xkbutil [toggle|set layout]"

